name: Test Automation WorkFlow

on:
  schedule:
    - cron: 30 13 1 * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false    
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Create logs folder
      run: mkdir -p logs
      
    - name: Running Test Automation Framework with Maven
      run: mvn test -Dmaven.test.failure.ignore=true -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=true

    -  name: Upload Test logs
       if: always()
       uses: actions/upload-artifact@v4.6.2
       with:
        name: Test Logs
        path: target/surefire-reports/
        
    -  name: Upload SCreenshots as Artifacts
       if: always()
       uses: actions/upload-artifact@v4.6.2
       with:
        name: screenshots
        path: screenshots/

    -  name: Upload HTML Report as Artifact
       if: always()
       uses: actions/upload-artifact@v4.6.2
       with:
        name: html-reports
        path: report.html

    -  name: Notify Test Complettion
       run:  echo "Test Execution Completed"

    - name: Copy Report to gh-pages Folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R report.html  public/extent-reports/
        cp -R screenshots/ public/extent-reports/screenshots/
        ls -l


    - name: Deploy 🚀
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
       folder: public/extent-reports/
       token: ${{ secrets.DEPLOYMENT_SECRET }} 
       branch: gh-pages
       clean: true






   
   
